language: android
sudo: false
android:
    components:
        - tools
        - build-tools-24.0.3
        - android-23
        - extra-android-m2repository
script:
    - cd Pdf417MobiDemo
    - ./gradlew clean assembleRelease